### ISSUE TITLE
Mongokat is missing on pypi / pip fails

### ISSUE THREAD

**Issue by bloodywing** [pricingassistant/mongokat#10]
Hello,

I try to install mongokat in a fresh virtualenv with pip. What I've found out so far is that it is actually missing on pypi. 

Installing with:
`pip install https://github.com/pricingassistant/mongokat/archive/master.zip`
works though.

**Comment by sylvinus** [comment]
Can you try now? Thanks!

**Comment by bloodywing** [comment]
Looks good now.
