### ISSUE TITLE
Add mapping of keys to shorter values in DB

### ISSUE THREAD

**Issue by oz123** [pricingassistant/mongokat#13]
This feature could enhance performance, and save some space on the database. 
Humbledb has that feature, but what prevents me from using it, is the lack of type constraints.

```
from humbledb import Document

class HumbleDoc(Document):
    config_database = 'humble'
    config_collection = 'example'

    description = 'd'  # the attribute description is mapped to the key d in the database
    value = 'v'  # the attribute value is mapped to the key v in the database
```

**Comment by lafrech** [comment]
Note that the WiredTiger engine introduced with Mongo 3 makes this feature less critical: since WiredTiger allows compression, there is no need to use short keys.

**Comment by oz123** [comment]
Compressing is still expensive. Plus, a key with 4 characters takes less space than a longer key. 
I understand that disk space isn't that expensive, but the ability to have all your working set in the RAM is important, and this is still the bottle neck in many computers.

**Comment by sylvinus** [comment]
Short key names will indeed be relevant for a while, at least until everyone migrates to WiredTiger.

However I don't feel it's a feature we want in mongokat, though I'd welcome adding a recipe for doing it in the doc, for instance by extending the Document class.

**Comment by sylvinus** [comment]
I just added an example of how to subclass the Document class to allow for limited field aliases. Happy to  review any further implementation.
