### ISSUE TITLE
Upgrade to pymongo 3.3.0

### ISSUE THREAD

**Issue by sylvinus** [pricingassistant/mongokat#19]
We should re-import the latest bson module files and re-apply our patches

**Comment by odedfos** [comment]
Is this task in the roadmap of this project?

**Comment by zoharby** [comment]
+1

**Comment by sylvinus** [comment]
I don't have an immediate need for this but I can review a patch if someones wants to do it

**Comment by maelorn** [comment]
fixed by https://github.com/pricingassistant/mongokat/pull/23
