### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by sylvinus** [pricingassistant/mongokat#5]

**Comment by goanpeca** [comment]
Any timeline for this?

**Comment by sylvinus** [comment]
We're not actively working on it as we don't use py3 but we'd gladly accept patches. Shouldn't be too hard as pymongo is already OK.

**Comment by sylvinus** [comment]
Wow! Thanks to @Liwink and @monnierj for the Pull Requests! Impressed to have 2 of them in just a couple days :-)

One seems to be using six, the other not. Let's discuss here which approach is the best for the project?

**Comment by sylvinus** [comment]
Fixed by #18 :-)
